### ISSUE TITLE
Support review of someone else's annotation

### ISSUE THREAD

**Issue by dosumis** [cellannotation/cell-annotation-schema#100]
Suggested fields from CAP:

Field Name | Value
-- | --
time | Timestamp when the user saved/published/submitted the reviews. (We’re still figuring this out; cf Question #1)
cap_username | CAP username of the Reviewer who provided the feedback
name | Full name of the person who provided the review, [FIRSTNAME LASTNAME]
cellannotation_setname | The name of the labelset. Directly from the CAS schema. https://github.com/cellannotation/cell-annotation-schema/blob/main/docs/cap_anndata_schema.mdhttps://github.com/cellannotation/cell-annotation-schema/blob/main/build/CAP_schema.md
review | String. Either “Agree” or “Disagree”. This records whether the user agreed or disagreed.
cell_label | Directly from CAS schema.
cell_fullname | Directly from CAS schema.
cell_ontology_term | Directly from CAS schema.
cell_ontology_term_id | Directly from CAS schema.
explanation | Free-text of the message explaining the reasoning why the user disagreed. If “Agree”, then put in NA.

This will be supported by CAP - see https://capdevelopment.atlassian.net/wiki/spaces/CAP/pages/473464834/Feedback+on+Cell+Annotations (Link for CAP members only)

**Comment by dosumis** [comment]
CC @evanbiederstedt 

Some notes:

TBD: Do we need separate review objects that can be attached to annotations (flattened as needed) or should we just add more fields to annotation objects?  I favour the former as with these we can easily support comments from  multiple reviewers.

**Comment by evanbiederstedt** [comment]
> Do we need separate review objects that can be attached to annotations (flattened as needed)

That's my proposal. These could be *tsv files users could download. 

It's simple + quick.

**Comment by dosumis** [comment]
Sketching our the 2 options more explicitly.

1. review object list nested inside each annotation object:

```YAML
annotation:
  cell_label:
  labelset:  
  cell_fullname: 
  cell_ontology_term: 
  cell_ontology_term_id:
  #...
   reviews: 
      type: array
      Items: $ref: review

review:
  time: 
  name: 
  review: "String. Either “Agree” or “Disagree”. This records whether the user agreed or disagreed."
  explanation: "Free-text of the message explaining the reasoning why the user disagreed. If “Agree”, then put in NA."
```

Array of reviews at top level:

```YAML
reviews: 
      type: array
      Items: $ref: review
review: 
  time: 
  name: 
  cell_label:
  labelset:  
  cell_fullname: 
  cell_ontology_term; 
  cell_ontology_term_id; 
  review: 
  explanation: 
```
In this second case we have a lot of duplicate info with annotation objects.  Link presumably works on cell_label + labelset as keys.  

In both cases, flattening into a table for reporting purposes is easy.
